name: FullStack CI

on:
  pull_request:
    paths:
      - 'Server/**'
      - 'Client/**'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: Client
        run: npm ci

      - name: Lint frontend
        working-directory: Client
        run: npm run lint

      - name: Build frontend
        working-directory: Client
        run: npm run build


  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore solution
        run: dotnet restore Server/Server.sln

      - name: Build solution
        run: dotnet build Server/Server.sln --no-restore --configuration Release

      - name: Generate appsettings.json
        run: |
          cat <<EOF > Server/Api/appsettings.json
          {
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*",
            "Db": "${{ secrets.DB_CONNECTION_STRING }}"
          }
          EOF

      - name: Run backend tests
        working-directory: Server/Test
        run: |
          dotnet test Test.csproj \
            --configuration Release \
            --logger "trx;LogFileName=test_results.trx"

      - name: Publish API
        run: dotnet publish Server/Api/Api.csproj -c Release -o ./publish

      - name: Build Backend Docker image
        working-directory: Server
        run: docker build -t examproject-backend/server .
